### Java异常解析
Java将异常当作一个对象来处理，并设定了一个基类作为异常类的超类java.lang.Throwable。   
它有两个子类java.lang.Error和java.lang.Exception，分别表示错误和异常。

#### Error
Error是程序无法处理的错误，例如`VirtualMachineError`、`OutOfMemoryError`、`StackOverflowError`、`ThreadDeath`等，这些错误发生时，JVM一般会选择终止运行。

#### Exception
Exception是程序可以处理的异常，可以分为运行时异常和非运行时异常：

* 运行时异常是`java.lang.RuntimeException`类及其子类异常，如`NullPointerException`、`IndexOutOfBoundsException`等，这些异常是非受检异常，程序中可以捕获处理，也可以不处理。这些异常一般是由于程序逻辑错误导致的，程序应从逻辑的角度尽量避免此类异常的发生。

* 非运行时异常是`RuntimeException`以外的异常，类型上属于Exception及它的子类，如`IOException`、`SQLException`及其他用户自定义的Exception异常等。这些异常是受检异常，必须进行处理，如果不处理，则程序编译不能通过。

一般情况下，不要自定义受检异常。

### 异常处理
Java异常处理有几个关键字，`try`，`catch`，`finally`，`throw`，`throws`。

* 异常处理基本语法
	
	```
	try {
	  //尝试运行的代码
	} catch (异常类型 异常变量名) {
	  //异常处理代码
	} finally {
	  //异常发生，方法返回之前，总是要执行的代码
	}
	```
	
  1. try语句块，表示要尝试运行代码，try语句块中代码受异常监控，其中代码发生异常时，会抛出异常对象。
  2. catch语句块会捕获try代码块中发生的异常并在其代码块中做异常处理，catch语句带一个Throwable类型的参数，表示可捕获异常类型。当try中出现异常时，catch会捕获到发生的异常，并和自己的异常类型匹配，若匹配，则执行catch块中代码，并将catch块参数指向所抛的异常对象。
  3. catch语句可以有多个，用来匹配多个中的一个异常，一旦匹配上后，就不再尝试匹配别的catch块了。
  4. finally语句块是紧跟catch语句后的语句块，这个语句块总是会在方法返回前执行，而不管是否try语句块是否发生异常。并且这个语句块总是在方法返回前执行。目的是给程序一个补救的机会。这样做也体现了Java语言的健壮性。

* 几个注意的问题
  1. `try`，`catch`，`finally`三个语句块不能单独使用，可以有以下三种组合，catch可以有大于等于一个，finally最多一个：   
     * `try...catch...finally`
     * `try...catch`
     * `try...finally`
  
  2. try、catch、finally三个代码块中变量的作用域为代码块内部，分别独立而不能相互访问。如果要在三个块中都可以访问，则需要将变量定义到这些块的外面。
  3. 多个catch块时候，只会匹配其中一个异常类并执行catch块代码，而不会再执行别的catch块，并且匹配catch语句的顺序是由上到下。 

* `throw`&`throws`关键字
  1. throw关键字是作用于方法体内部，用来抛出一个Throwable类型的异常。
	 * 如果抛出了**检查异常**，则还应在方法头部声明方法可能抛出的异常类型。该方法的调用者也必须检查处理抛出的异常。如果方法层层都上抛获取的异常，最终JVM会处理，打印异常消息和堆栈信息
	 * 如果抛出的是Error或RuntimeException，则方法的调用者可以选择处理该异常

  2. throws关键字作用于方法头部声明抛出异常，声明方法可能抛出哪些异常。

     * 仅当抛出了**检查异常**，该方法的调用者才必须处理或重新抛出异常